
* Nemesis

Maintain configs and a list of the various programs that have been installed during the time.


** Programs
   
*** Neet Programms rewritten in Rust
    tldr similar to man
    
**** find -> ripgrep, called : rg 

**** starship

**** exa -> ls

**** cat -> bat

**** find -> fd

**** ps -> procs

*** Window Manager

Got stuck in dwm. Just suckless.

*** Terminal

**** kitty

Best terminal emulator so far I've tried.

**** Alacritty
- Compirse /picom-jonaburg-git 0.1-4/
- Located in awesome config directory

**** [ ] fish
Maybe a good choice is /omf/ (oh-my-fish)
- omf

**** zsh

**** spaceship prompt

Just Awesome

*** Editor

**** Emacs
- pdfview
- programming
- text
- ...

*** Programming

**** Compiler

***** gcc

- gdb (debug)

***** clang

- llvm
- lldb (debug)

**** Building

- make
- cmake


*** Picture & Video

- SimpleScreenRecord
- feh
- mpv
- youtube-dl
- spotify
- deadbeef
- variety

**** olivia    (streaming)
build with yay (AUR)

*** Command Dispatcher

- rofi
- dmenu

*** Office

**** ranger (never found again but ranger for terminal jumping the file system around is awesome
)
pdf utility for sorting out some pages

**** pdftk

split and combine pdf

** Configs

*** ZSH

Prerequsite is the starship promp
* God to know about

** Gnome issues

*** Control center

    settings gone -> solution: reinstall =gnome-control-center=

    found in [[https://askubuntu.com/questions/337335/system-settings-is-missing]]
